# Hardware-specific configuration for the 'misato' host
# Generated by nixos-generate-config, typically not manually edited
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  # Import standard hardware scan module
  # Automatically detects hardware and adds necessary kernel modules/configs
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules needed in the initial ramdisk (initrd)
  # These are required to mount the root filesystem (including LUKS decryption)
  boot.initrd.availableKernelModules = [
    "xhci_pci" # USB 3.0 controller support
    "ahci" # SATA controller support
    "usb_storage" # USB mass storage support
    "sd_mod" # SCSI disk support (for SATA drives)
    "rtsx_pci_sdmmc" # Realtek card reader support
  ];

  # Additional kernel modules to load in initrd (none needed)
  boot.initrd.kernelModules = [];

  # Kernel modules to load after boot (none needed)
  boot.kernelModules = [];

  # Out-of-tree kernel packages (none needed)
  boot.extraModulePackages = [];

  # System architecture
  # mkDefault allows override via command line if needed
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Intel CPU microcode updates
  # Provides security patches and bug fixes from Intel
  # mkDefault ensures it's only enabled when redistributable firmware is allowed
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
